### ISSUE TITLE
UI: Update the layout of the method list 

### ISSUE THREAD

**Issue by maudnals** [decentralized-identity/universal-resolver-frontend#10]
Hi there!

I see 2 minor issues with the list of methods in the current UI:
* As the list is getting longer (which is great - and it will only get longer), the button "Add your driver" is not showing anymore;
* The methods look clickable when in fact there are not (I saw a few people try to click them - me too!).

A quick mockup with some ideas is attached. No big changes; I thought that agreeing on a mockup first would save us all time over implementing changes directly.

![Group 2](https://user-images.githubusercontent.com/9762897/72165010-0b574a80-33c7-11ea-9e8d-f4b302d0a755.jpg)

What do you think @peacekeeper ?

**Comment by OR13** [comment]
I agree with this.

I'd prefer a separate page with supported drivers, and a call to action on the first page for "Supported Drivers" and "Add your driver"... This will allow us to minimize information for the default use case of just resolving things.

**Comment by peacekeeper** [comment]
@maudnals good idea, yes I was also beginning to worry about the size of the list.. I think the mock-up looks great.

**Comment by maudnals** [comment]
Hi @peacekeeper , @OR13 , thanks for your feedback!

@OR13, a separate page would be great. We could even imagine adding links next to each method for users to navigate to the spec/doc of each.

Yet a separate page would be a bit more work (e.g. add navigation); I feel we should quickly fix the display bug first since it undermines the universal resolver's functionality by hiding some supported methods. So we could do this iteratively: 
(1) **Fix** the current issue with the layout;
(2) **Improve** the layout with a second page as suggested.

I've opened a PR for the fix (1). 
It implements the mockup: https://github.com/decentralized-identity/universal-resolver-frontend/pull/11
Happy to help out with (2) later on!

What do you think?

**Comment by OR13** [comment]
@maudnals I agree with your approach. PR looks good, @peacekeeper on you :)
