### ISSUE TITLE
Supported Methods: not accurate..

### ISSUE THREAD

**Issue by PeterTheOne** [decentralized-identity/universal-resolver-frontend#15]
Shouldn't `did:ethr` be supported?

Can't we derive this https://github.com/decentralized-identity/universal-resolver-frontend/blob/master/src/components/App.jsx#L12-L31 list from the config ("see configuration") pattern?

**Comment by BernhardFuchs** [comment]
At the moment our config for backend and frontend applications are not synced automatically. So it can happen that the API supports a did-method which is not listed in the frontend yet. We are aware of this and have automatic synchronization on our roadmap.
