### ISSUE TITLE
Prod build does not return images

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/universal-resolver-frontend#17]
I followed the steps in the readme to build the docker image and this is what I get:

It works, except that the logo and the favicon return a 404

<img width="1440" alt="Screenshot 2020-03-21 at 23 49 09" src="https://user-images.githubusercontent.com/7913565/77229030-b4dc6880-6bce-11ea-9f21-caac79e76cdd.png">

**Comment by philpotisk** [comment]
@gjgd I added the missing image folder to the Docker file, which should fix this issue. Thanks for spotting this problem.

**Comment by gjgd** [comment]
Thanks @philpotisk , that fixed the logo issue but the favicon still wasn't showing. I submitted a PR: https://github.com/decentralized-identity/universal-resolver-frontend/pull/18
