### ISSUE TITLE
page not loaded

### ISSUE THREAD

**Issue by remyahalza** [decentralized-identity/universal-resolver-frontend#37]
i use the production mode,

created image and run the docker image 
![image](https://user-images.githubusercontent.com/68893691/115558575-efc63980-a2c3-11eb-884b-5c8463b14328.png)

page not loaded

**Comment by remyahalza** [comment]
![Uploading image.png…]()

**Comment by BernhardFuchs** [comment]
Can you pls provide logs from docker? Maybe this links helps https://docs.docker.com/docker-for-windows/troubleshoot/

**Comment by peacekeeper** [comment]
@remyahalza do you still have problems with this? Or can we close the issue?

**Comment by peacekeeper** [comment]
Assuming that this has been solved, closing. Feel free to re-open if you still have issues.
