### ISSUE TITLE
Update UX to Support Linking

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/universal-resolver-frontend#5]
https://github.com/decentralized-identity/universal-resolver/issues/54

It would be nice to be able to easily link to a Resolved DID.

There should be a button with the text "Share" or similar, that copies a url of the form:

https://uniresolver.io/#did:btcr:xxcl-lzpq-q83a-0d5

It should be accent colored to draw attention to it.

There should also be a QR Code which maps to an endpoint which either resolves to https://uniresolver.io/#did:btcr:xxcl-lzpq-q83a-0d5 or the json representation, depending on request headers.

This will allow clients to decide if they want to show the DID or get its data.

**Comment by brianorwhatever** [comment]
hmm was going to close this as #67 appears to do this however the QR code that is displayed right now using my iOS camera app displays "no usable data"

**Comment by peacekeeper** [comment]
Well the QR code only contains the DID itself, e.g. `did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w`. This was an experimental idea, I imagine that your iOS scanner and most other apps doesn't understand this.

So perhaps it would make more sense to put the same URL into the QR code that you also get from the new "Copy link to result" button, i.e. `https://dev.uniresolver.io/#did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w`?

**Comment by OR13** [comment]
I generally tend to encode DIDs as URLs so that any phone that scans them, can open them as a link.

**Comment by peacekeeper** [comment]
This functionality was added in https://github.com/decentralized-identity/universal-resolver-frontend/pull/65 and in https://github.com/decentralized-identity/universal-resolver-frontend/commit/a6da930ca0bff21beadfadabfc1c321ddfa757b7. Closing.
