### ISSUE TITLE
Copy is not enabled 

### ISSUE THREAD

**Issue by vongohren** [decentralized-identity/universal-resolver-frontend#66]
This pr was not tested
https://github.com/decentralized-identity/universal-resolver-frontend/pull/65

And it seems my assumption on enabling did not work.

How can I test with a live version on the frontend? Meaning a server to respond to.

Can I use dev version or something?

I will not be on a computer until tomorrow afternoon

**Comment by peacekeeper** [comment]
For testing, it should be possible to run both universal-resolver and universal-resolver-frontend locally.

Maybe you could try to fix this with another PR once you're back at your computer?

**Comment by vongohren** [comment]
Sounds good! Yeah I will. I just left this issue to track it and make you aware of it!

**Comment by vongohren** [comment]
<img width="642" alt="Screen Shot 2022-11-13 at 23 06 30" src="https://user-images.githubusercontent.com/1012055/201547920-dbf08a0f-6f63-401e-bad6-a0d8e2ed4931.png">

I took this approach

But this solves it: https://github.com/decentralized-identity/universal-resolver-frontend/pull/67

**Comment by vongohren** [comment]
Does it take some time before things are deployed? Since the bug is still there but the PR has been merged?

**Comment by vongohren** [comment]
@BernhardFuchs @peacekeeper ?

**Comment by peacekeeper** [comment]
The deployment is manual. @BernhardFuchs can you redeploy the frontend at https://dev.uniresolver.io/?

**Comment by BernhardFuchs** [comment]
@vongohren The image for the frontend is not deployed automatically after merging a branch. Forgot about that limitation and didn't re-deploy it manually.  

I just did a deployment of the latest image build at your last commit https://github.com/decentralized-identity/universal-resolver-frontend/commit/d89d79b148fa6bc0efa202dd2e8b03af0235ab29

**Comment by vongohren** [comment]
Perfect, can confirm its working now. Closing with this comment
