### ISSUE TITLE
publicKeyMultibase doesn't appear to be showing in the did document resolver

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/universal-resolver-frontend#69]
<img width="743" alt="image" src="https://user-images.githubusercontent.com/7122708/202576957-f20a49b4-beb8-4497-9d19-0467109a49db.png">

**Comment by peacekeeper** [comment]
Hmm `did:web:aviary.pub` seems to be down right now, so I can't try it myself. Could you share the full DID document? 

Normally, "publicKeyMultibase" should be supported by the UI, see here: https://github.com/decentralized-identity/universal-resolver-frontend/blob/main/src/components/result/VerificationMethod.jsx#L15

**Comment by brianorwhatever** [comment]
Yes, apologies that domain is my ngrok tunnel domain so I need my local setup booted. Here is the full document
```
{
  "@context": [
    "https://www.w3.org/ns/did/v1",
    "https://w3id.org/security/suites/jws-2020/v1"
  ],
  "controller": "did:web:aviary.pub",
  "id": "did:web:aviary.pub",
  "keyAgreement": [
    "did:web:aviary.pub#1"
  ],
  "service": [
    {
      "accept": [
        "didcomm/v2"
      ],
      "id": "#didcomm",
      "serviceEndpoint": "https://aviary.pub/didcomm",
      "type": "DIDCommMessaging"
    }
  ],
  "verificationMethod": [
    {
      "controller": "did:web:aviary.pub",
      "id": "did:web:aviary.pub#0",
      "publicKeyMultibase": "z8FRmkyRH9xAsLCk51yXN2Qy6uq4eN4iAesa3v3Hv889v",
      "type": "Ed25519VerificationKey2020"
    },
    {
      "controller": "did:web:aviary.pub",
      "id": "did:web:aviary.pub#1",
      "publicKeyMultibase": "z7bNjXnt3EXhpy7UdzZUANa2CsBFpzKGFXsgvkBd9iHGo",
      "type": "X25519KeyAgreementKey2020"
    }
  ]
}
```

**Comment by brianorwhatever** [comment]
Ok, I think I've determined this is a json-ld problem after looking at it on the playground. I guess I need a context for those suite types. Searching for them now..

**Comment by brianorwhatever** [comment]
hmm added "https://www.w3id.org/security/suites/x25519-2020/v1" as a context but that doesn't seem to resolve the issue

**Comment by peacekeeper** [comment]
@brianorwhatever I think this has been fixed now in https://github.com/decentralized-identity/universal-resolver-frontend/commit/1a17332f532949db32b69da44eaff9854266bb09.

The latest version is already deployed at https://dev.uniresolver.io/. Could you check, and if you agree, close the issue?

**Comment by brianorwhatever** [comment]
Looks great, thanks for the fix @peacekeeper !
